# TCL File Generated by Component Editor 18.1
# Sun Dec 15 11:38:38 CET 2024
# DO NOT MODIFY


# 
# Verin_Avalon "Verin_Avalon" v1.0
#  2024.12.15.11:38:38
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Verin_Avalon
# 
set_module_property DESCRIPTION ""
set_module_property NAME Verin_Avalon
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Verin_Avalon
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL verin_avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file verin_avalon.vhd VHDL PATH verin_avalon.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 chipselect_in chipselect Input 1
add_interface_port avalon_slave_0 write_n write_n Input 1
add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 address address Input 4
add_interface_port avalon_slave_0 readdata readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point data_in
# 
add_interface data_in conduit end
set_interface_property data_in associatedClock clock
set_interface_property data_in associatedReset ""
set_interface_property data_in ENABLED true
set_interface_property data_in EXPORT_OF ""
set_interface_property data_in PORT_NAME_MAP ""
set_interface_property data_in CMSIS_SVD_VARIABLES ""
set_interface_property data_in SVD_ADDRESS_GROUP ""

add_interface_port data_in data_in beginbursttransfer Input 1


# 
# connection point out_pwm
# 
add_interface out_pwm conduit end
set_interface_property out_pwm associatedClock clock
set_interface_property out_pwm associatedReset ""
set_interface_property out_pwm ENABLED true
set_interface_property out_pwm EXPORT_OF ""
set_interface_property out_pwm PORT_NAME_MAP ""
set_interface_property out_pwm CMSIS_SVD_VARIABLES ""
set_interface_property out_pwm SVD_ADDRESS_GROUP ""

add_interface_port out_pwm out_pwm writeresponsevalid_n Output 1


# 
# connection point cs
# 
add_interface cs conduit end
set_interface_property cs associatedClock clock
set_interface_property cs associatedReset ""
set_interface_property cs ENABLED true
set_interface_property cs EXPORT_OF ""
set_interface_property cs PORT_NAME_MAP ""
set_interface_property cs CMSIS_SVD_VARIABLES ""
set_interface_property cs SVD_ADDRESS_GROUP ""

add_interface_port cs cs writeresponsevalid_n Output 1


# 
# connection point clk_1M
# 
add_interface clk_1M conduit end
set_interface_property clk_1M associatedClock clock
set_interface_property clk_1M associatedReset ""
set_interface_property clk_1M ENABLED true
set_interface_property clk_1M EXPORT_OF ""
set_interface_property clk_1M PORT_NAME_MAP ""
set_interface_property clk_1M CMSIS_SVD_VARIABLES ""
set_interface_property clk_1M SVD_ADDRESS_GROUP ""

add_interface_port clk_1M un_M writeresponsevalid_n Output 1


# 
# connection point sens_out
# 
add_interface sens_out conduit end
set_interface_property sens_out associatedClock clock
set_interface_property sens_out associatedReset ""
set_interface_property sens_out ENABLED true
set_interface_property sens_out EXPORT_OF ""
set_interface_property sens_out PORT_NAME_MAP ""
set_interface_property sens_out CMSIS_SVD_VARIABLES ""
set_interface_property sens_out SVD_ADDRESS_GROUP ""

add_interface_port sens_out sens_out writeresponsevalid_n Output 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1

